site_name: AIMMS Documentation
theme:
  name: material

nav:
  - Introduction: index.md
  - Getting Started:
      - Installation: install.md
      - Configuration: config.md
  - Features:
      - Feature A: feature-a.md
      - Feature B: feature-b.md